= Projecte 1 DAW

== Integrants del grup
****
* https://gitlab.com/ortiz.leal.roger[**Roger Ortiz Leal**] (`ortiz.leal.roger@alumnat.copernic.cat`)

* https://gitlab.com/gonzalez.guix.ramon[**Ramón González Guix**] (`gonzalez.guix.ramon@alumnat.copernic.cat`)

* https://gitlab.com/ibenitez[**Ismael Benítez Martínez**] (`ibenitez@alumnat.copernic.cat`)
****

== **R01**: Guia d'estils de l'aplicació
=== Paleta de colors

=== Tipografia

==== Logo: 
[source, css]
----
{
    font-family: Cinzel;
    font-weight: 50px;
    font-style: normal;
}
----

==== General:
[source, css]
----
{
    font-family: Roboto;
    font-weight: 50px;
    font-style: normal;
}
----

==== Categories: 
[source, css]
----
{
    font-family: Roboto;
    font-weight: 50px;
    font-style: normal;
}
----

==== Títols:
[source, css]
----
{
    font-family: Roboto;
    font-weight: 50px;
    font-style: normal;
}
----

==== Subtítols: 
[source, css]
----
{
    font-family: Roboto;
    font-weight: 50px;
    font-style: normal;
}
----

== **R03**: Entorns de desplegament a Isard

Per realitzar aquest projecte, utilitzarem https://isardvdi.com/[**IsardVDI**] com a entorn de desenvolupament i desplegament.

Aquesta secció de la memòria està dedicada a explicar com configurar un entorn de desenvolupament i desplegament a IsardVDI.

IMPORTANT: S'assumeix que l'usuari ja té un compte a IsardVDI i que ha configurat dos servidors.

=== Instal·lació del servidor SSH
Per poder connectar-nos de forma remota a les màquines virtuals, necessitem instal·lar un servidor SSH:

1. Abans de res, actualitzem els paquets del sistema amb la comanda `sudo apt update`. Això assegura que tenim la darrera versió dels paquets disponibles.

2. Instal·lem el servidor SSH amb la comanda `sudo apt install openssh-server`.

3. Un cop instal·lat, iniciem el servei amb la comanda `sudo systemctl start ssh`.

4. Per comprovar que el servei s'ha iniciat correctament, executem `sudo systemctl status ssh`.

5. Si ho hem fet tot correctament, veurem un missatge semblant a aquest:
[source, bash]
----
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-10-14 10:00:00 CEST; 1h 30min ago
----
