# Referència: https://github.com/Vettabase/vagrant-mariadb-examples
BOX = ENV["BOX"] || "ubuntu/bionic64"

Vagrant.configure("2") do |config|
    config.vm.box = BOX
    config.vm.box_check_update = true
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.synced_folder ".", "/Vagrant"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.customize ["modifyvm", :id, "--name", "subasterra-local"]
        vb.customize ["modifyvm", :id, "--memory", 1024 * 2] # 2GB
        vb.customize ["modifyvm", :id, "--cpuhotplug", "on"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.customize ["modifyvm", :id, "--vram", "8"] # 4MB
        vb.customize ['modifyvm', :id, '--clipboard', "bidirectional"]
    end

    config.vm.provision :shell, path: "bootstrap.sh"
end