# Referència: https://github.com/Vettabase/vagrant-mariadb-examples
BOX = ENV["BOX"] || "ubuntu/bionic64"

Vagrant.configure("2") do |config|
    config.vm.box = BOX
    config.vm.box_check_update = true
    config.vm.network "forwarded_port", guest: 3306, host: 1234
    config.vm.synced_folder ".", "/Vagrant"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.customize ["modifyvm", :id, "--name", "subasterra-local"]
        vb.customize ["modifyvm", :id, "--memory", 1024 * 2] # 2GB
        vb.customize ["modifyvm", :id, "--cpuhotplug", "on"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.customize ["modifyvm", :id, "--vram", "8"] # 4MB
        vb.customize ['modifyvm', :id, '--clipboard', "bidirectional"]

        # Referència: https://github.com/hashicorp/vagrant/issues/11777#issuecomment-661076612
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    end

    config.vm.provision :shell, path: "bootstrap.sh"
end